# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://cdn.cocoapods.org/'

target 'PasswordManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PasswordManager
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
